name: modux
description: Move Redux

version: 0.9.0

environment:
  sdk: ">=2.1.0-dev.9.4 <3.0.0"

dependencies:
  built_value: ^6.3.1
  built_collection: ^4.1.0
  logging: ^0.11.3+2
  web_socket_channel: ^1.0.9
  rxdart: ^0.21.0

dev_dependencies:
  analyzer: ^0.34.3
  build: ^1.0.3
  build_runner: ^1.1.3
  test: ^1.5.1
  mockito: ^4.0.0
  built_value_generator:
    path: ../generators/built
